### ISSUE TITLE
(node:3288) UnhandledPromiseRejectionWarning: TypeError: data.lessonData is not iterable

### ISSUE THREAD

**Issue by SevenDice** [20lives/FrontendMastersDownloader#1]
$ node femdl.js -u '@gmail.com' -p '***' -c 'functional-js-fundamentals'
Course Slides
(node:3288) UnhandledPromiseRejectionWarning: TypeError: data.lessonData is not iterable
    at dlTranscripts (C:\FrontendMastersDownloader-master\femdl.js:50:28)
    at dlCourse (C:\FrontendMastersDownloader-master\femdl.js:34:3)
    at run (C:\FrontendMastersDownloader-master\femdl.js:23:11)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
(node:3288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3288) UnhandledPromiseRejectionWarning: TypeError: data.lessonData is not iterable
    at dlVideos (C:\FrontendMastersDownloader-master\femdl.js:40:26)
    at dlCourse (C:\FrontendMastersDownloader-master\femdl.js:35:9)
    at run (C:\FrontendMastersDownloader-master\femdl.js:23:11)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
(node:3288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
downloaded (1/1): Course Slides.pdf

**Comment by 20lives** [comment]
The project wasn't updated for over 2 years, FED probably changed their website so this probably isn't working anymore.
