### ISSUE TITLE
Error from inquirer library

### ISSUE THREAD

**Issue by KoichaDev** [20lives/FrontendMastersDownloader#13]
I tried to run `npm install` to update the node_modules, but for some reason. It still doesn't work. 

This is the code:

```
import inquirer from 'inquirer';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)        
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontendmasters-downloader@0.3.1 start: `node src/index.js`
npm ERR! Exit status 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Khoi\AppData\Roaming\npm-cache\_logs\2020-09-07T00_07_57_886Z- output above.debug.log
```

Can you pleases fix this?

**Comment by jk7g14** [comment]
did you fix this? I have a same problem ;-<

**Comment by pedrosimao** [comment]
I am facing the same bug.

**Comment by pedrosimao** [comment]
Ok, solved by updating node to the latest version...
