### ISSUE TITLE
ffmpeg was killed with signal SIGABRT

### ISSUE THREAD

**Issue by miminas** [20lives/FrontendMastersDownloader#19]
Script was working fine but as of today I am getting this error:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg was killed with signal SIGABRT
    at ChildProcess.<anonymous> (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:268:20)
    at next (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:4582:24)
    at /Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:321:20
    at wrapper (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:268:20)
    at next (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:4582:24)
    at /Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/async/dist/async.js:321:20
    at /Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at handleExit (/Users/USER/.npm/_npx/6287/lib/node_modules/frontendmasters-downloader/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
```

**Comment by miminas** [comment]
I tried today again and now I get the following error:

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/USER/.npm/_npx/48919/lib/node_modules/frontendmasters-downloader/node_modules/node-ffprobe/lib/ffprobe.js:36:40)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`

**Comment by 20lives** [comment]
It will be more helpful if you give us more information: OS, node version, and the full log.

**Comment by miminas** [comment]
Running using NPX on MacOS 10.15.7, node version 14.4.0 and the log is the one I pasted. Is there a way to get a more verbose log?

**Comment by 20lives** [comment]
every printout after `npx frontendmasters-downloader`

**Comment by 20lives** [comment]
and also ffmpeg and ffprobe versions.

**Comment by miminas** [comment]
@20lives I thought that the script contained everything it needed to work, so I did not think that the problem was with ffmpeg. I tried removing it and reinstalling it via homebrew and now the script works fine. I do not know what went wrong though in the first place! Thanks for your time and effort.

**Comment by 20lives** [comment]
glad I could help.
