### ISSUE TITLE
Unable to download (map of uindinfined)

### ISSUE THREAD

**Issue by raveltan** [20lives/FrontendMastersDownloader#24]
```
(node:17449) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at extractPrograms (file:///home/ravel/.npm/_npx/17449/lib/node_modules/frontendmasters-downloader/src/programsExtractor.js:8:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (file:///home/ravel/.npm/_npx/17449/lib/node_modules/frontendmasters-downloader/src/index.js:46:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
I got this error message when downloading, any idea about how to fix this error?

**Comment by 20lives** [comment]
this seems like an error in running `ffprobe`, try reinstalling `ffmpeg``.

**Comment by raveltan** [comment]
ffprobe is available in my path,

```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
```

and this is the output ffprobe
I'm using Pop Os 20.04 btw

**Comment by raveltan** [comment]
I'm not sure why, but now the program is now working even though nothing is changed

**Comment by 20lives** [comment]
did you reinstalled ffmpeg?
