### ISSUE TITLE
Can't download course with name that include a colon (e.g Javascript: Fundamentals . . . )

### ISSUE THREAD

**Issue by andres-sumihe** [20lives/FrontendMastersDownloader#5]
I try to download some course with a colon in the course name but i got error 

``` bash
(node:13500) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir './JavaScript: From Fundamentals to Functional JS, v2/'
    at Object.mkdirSync (fs.js:914:3)
    at Object.download (file:///C:/Users/Andflow/AppData/Roaming/npm-cache/_npx/13500/node_modules/frontendmasters-downloader/downloader.js:25:8)
    at run (file:///C:/Users/Andflow/AppData/Roaming/npm-cache/_npx/13500/node_modules/frontendmasters-downloader/index.js:58:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
OS : Windows 10
Node Version : 12.18.0
NPX Version : 6.14.4

i assumed that the error happen because program cant make a directory with the a colon (Windows Files Name Rule)

im sorry if this issue was writen in an incorrect way

**Comment by 20lives** [comment]
Hi @andres-sumihe,
Thank you for opening this issue, I didn't sanitize the course name, will fix it soon.

**Comment by andres-sumihe** [comment]
Oke thanks for your response
i'll wait for the update

**Comment by 20lives** [comment]
Fixed.
