### ISSUE TITLE
FedHasher not working

### ISSUE THREAD

**Issue by MichaelMurithi** [20lives/FrontendMastersDownloader#54]
Hello,
I tried login in to the tool but I get the  following error in the command line:
![fed-error](https://user-images.githubusercontent.com/47428593/208761886-2ffe52fc-0e57-44da-b336-88d95a6a8b58.PNG)

I tried to debug the application by running it locally and I noticed that fedHasher() function below is not working: 
``` js
export default function (timestamp) {
  return fetch(`${constants.fedHasherUrl}${timestamp}`)
    .then((res) => res.json())
    .then((json) => json.hash);
}
```

This is because the application used with the `fedHasherUrl` here `'https://fed-hasher.herokuapp.com/timestamp='` is no longer available on `Heroku`.

Steps to reproduce:
1. Run the application (either using `npx` or `npm` locally)
2. Enter your email and password from the command line prompt.

**Comment by aprakash97** [comment]
Did it work locally (npm)? I tried but it didn't work.  Can you please share the steps briefly.

**Comment by lfkunzler** [comment]
Didn't work locally (with npm). Same issue. I haven't found any replacement for fed-hasher. Any suggestion?

**Comment by lfkunzler** [comment]
```
git clone https://github.com/20lives/frontendmastersDownloader.git
cd frondendmastersDownloader
npm install inquirer
npm run start
? Email address: ...
? Password: * * *

return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://fed-hasher.herokuapp.com/timestamp=1681218116 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at /tmp/frontendmastersDownloader/node_modules/node-fetch/lib/index.js:272:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateTimestamp (file:///tmp/frontendmastersDownloader/src/fedApi.js:19:10)
    at async Object.login (file:///tmp/frontendmastersDownloader/src/fedApi.js:51:3)
    at async run (file:///tmp/frontendmastersDownloader/src/index.js:15:22) {
  type: 'invalid-json'
}

Node.js v19.8.1
```

**Comment by NerdHusky** [comment]
It seems the heroku site that fedhasher is using doesn't work.
Is someone competent to make this project work again??
