### ISSUE TITLE
FetchError: invalid json response

### ISSUE THREAD

**Issue by nur557** [20lives/FrontendMastersDownloader#55]
```
? Email address: user@example.com
? Password: **********

/Users/user/.npm/_npx/f2d38d864951ebdc/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://fed-hasher.herokuapp.com/timestamp=1684656420 reason: Unexpected token < in JSON at position 0
    at /Users/user/.npm/_npx/f2d38d864951ebdc/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateTimestamp (file:///Users/user/.npm/_npx/f2d38d864951ebdc/node_modules/frontendmasters-downloader/src/fedApi.js:19:10)
    at async Object.login (file:///Users/user/.npm/_npx/f2d38d864951ebdc/node_modules/frontendmasters-downloader/src/fedApi.js:51:3)
    at async run (file:///Users/user/.npm/_npx/f2d38d864951ebdc/node_modules/frontendmasters-downloader/src/index.js:15:22) {
  type: 'invalid-json'
}

Node.js v18.13.0
```

**Comment by Karim-Muhammad** [comment]
I have same issue, i hope someone help us

**Comment by Hambob** [comment]
I have the same issue,

**Comment by ChillYao** [comment]
the same issue here.

**Comment by iZarrios** [comment]
I think the user's Heroku app is not running anymore.
![image](https://github.com/20lives/FrontendMastersDownloader/assets/60412985/bc81b6be-580a-436a-92ac-8296ddcee977)

**Comment by ydv-sahitya** [comment]
I am having the same issue as well, i tried in windows powershell and wsl, both giving me same  error.

**Comment by HazelDaniel** [comment]
yea, same issue

**Comment by Odaym** [comment]
same

**Comment by xXxcb** [comment]
Any update on this issue?
