### ISSUE TITLE
The requested module './utils.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by andres-sumihe** [20lives/FrontendMastersDownloader#6]
Hello, i run the scripts with npx and i got this error
``` bash
import sanitize from './utils.js';
       ^^^^^^^^
SyntaxError: The requested module './utils.js' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

cmiiw :)

i think that you forget to add default keyword when export or the {} in the import statement

**Comment by 20lives** [comment]
you are right, fixed.
