### ISSUE TITLE
Npx cannot run the project

### ISSUE THREAD

**Issue by Naughty-Monkey** [20lives/FrontendMastersDownloader#9]
The terminal log is as follows:
```
npx frontendmasters-downloader


npx: installed 38 in 5.606s
Must use import to load ES Module: /Users/xiangchen2011/.npm/_npx/11679/lib/node_modules/frontendmasters-downloader/index.js
```

**Comment by Naughty-Monkey** [comment]
BTW, running the cloned one:
```
npm ERR! missing script: start
```

**Comment by 20lives** [comment]
what version of npm are you using?

**Comment by Naughty-Monkey** [comment]
6.14.4

Twentylives <notifications@github.com> 于2020年7月23日周四 下午6:04写道：

**Comment by 20lives** [comment]
and node version?

**Comment by 20lives** [comment]
> BTW, running the cloned one:
> 
> ```
> npm ERR! missing script: start
> ```

I updated the missing command.

**Comment by Naughty-Monkey** [comment]
v12.16.3

**Comment by Naughty-Monkey** [comment]
```
❯ npm run start

> frontendmasters-downloader@0.1.1 start /Users/xiangchen2011/Desktop/code/frontendmastersDownloader
> node index.js

internal/modules/cjs/loader.js:1149
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/xiangchen2011/Desktop/code/frontendmastersDownloader/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontendmasters-downloader@0.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontendmasters-downloader@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by 20lives** [comment]
you are using a node version that is not supported, you should be using v13.2 or newer,
